
#GET ALL CONTACT
GET http://localhost:3000/users



### Get contact Id
GET http://localhost:3000/users/6731fa875010e9b7363c1f0d




POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json



{
  "email": "test5@example.com",
  "username": "john@john.com",
  "name": "Hello4",
  "ipaddress": "94.121.163.63"
}



### PUT contact
PUT http://localhost:3000/users/
Content-Type: application/json


{
  "email": "test5@example.com",
  "username": "john@john.com",
  "name": "Hello4",
  "ipaddress": "94.121.163.63"
} 


//Delete contact

DELETE http://localhost:3000/users/6731f7d75010e9b7363c1f09

 